#include "ganita/zero/GanitaZeroRepresentations.hpp"

#include "representations/GanitaZeroAdic.cpp"
#include "representations/GanitaZeroNeural.cpp"
#include "representations/GanitaZeroSymbolic.cpp"
#include "representations/GanitaZeroTower.cpp"
#include "representations/GanitaZeroMap.cpp"
#include "representations/GanitaZeroBinary.cpp"
#include "representations/GanitaZeroSub.cpp"
#include "representations/GanitaZeroHMM.cpp"
#include "representations/GanitaZeroTGF.cpp"
#include "representations/GanitaZeroGossip.cpp"
